sudo: false

language: go

cache: false
go:
  - 1.11.x

services: docker

env:
  - GO111MODULE=on

install:
  - go mod tidy
  - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin latest

script:
  - go build cmd/chat.go
  - go build cmd/db_queue.go
  - go test -v race ./...
  - golangci-lint -c .golangci.yml