// Code generated by protoc-gen-go. DO NOT EDIT.
// source: db.proto

package dbProto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserCreateRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserCreateRequest) Reset()         { *m = UserCreateRequest{} }
func (m *UserCreateRequest) String() string { return proto.CompactTextString(m) }
func (*UserCreateRequest) ProtoMessage()    {}
func (*UserCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8817812184a13374, []int{0}
}

func (m *UserCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserCreateRequest.Unmarshal(m, b)
}
func (m *UserCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserCreateRequest.Marshal(b, m, deterministic)
}
func (m *UserCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserCreateRequest.Merge(m, src)
}
func (m *UserCreateRequest) XXX_Size() int {
	return xxx_messageInfo_UserCreateRequest.Size(m)
}
func (m *UserCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserCreateRequest proto.InternalMessageInfo

func (m *UserCreateRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type UserModel struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	CreatedAt            int64    `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserModel) Reset()         { *m = UserModel{} }
func (m *UserModel) String() string { return proto.CompactTextString(m) }
func (*UserModel) ProtoMessage()    {}
func (*UserModel) Descriptor() ([]byte, []int) {
	return fileDescriptor_8817812184a13374, []int{1}
}

func (m *UserModel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserModel.Unmarshal(m, b)
}
func (m *UserModel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserModel.Marshal(b, m, deterministic)
}
func (m *UserModel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserModel.Merge(m, src)
}
func (m *UserModel) XXX_Size() int {
	return xxx_messageInfo_UserModel.Size(m)
}
func (m *UserModel) XXX_DiscardUnknown() {
	xxx_messageInfo_UserModel.DiscardUnknown(m)
}

var xxx_messageInfo_UserModel proto.InternalMessageInfo

func (m *UserModel) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserModel) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserModel) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

type ChatCreateRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Users                []int64  `protobuf:"varint,2,rep,packed,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatCreateRequest) Reset()         { *m = ChatCreateRequest{} }
func (m *ChatCreateRequest) String() string { return proto.CompactTextString(m) }
func (*ChatCreateRequest) ProtoMessage()    {}
func (*ChatCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8817812184a13374, []int{2}
}

func (m *ChatCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatCreateRequest.Unmarshal(m, b)
}
func (m *ChatCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatCreateRequest.Marshal(b, m, deterministic)
}
func (m *ChatCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatCreateRequest.Merge(m, src)
}
func (m *ChatCreateRequest) XXX_Size() int {
	return xxx_messageInfo_ChatCreateRequest.Size(m)
}
func (m *ChatCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChatCreateRequest proto.InternalMessageInfo

func (m *ChatCreateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ChatCreateRequest) GetUsers() []int64 {
	if m != nil {
		return m.Users
	}
	return nil
}

type ChatModel struct {
	Id                   int64        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Users                []*UserModel `protobuf:"bytes,3,rep,name=users,proto3" json:"users,omitempty"`
	CreatedAt            int64        `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ChatModel) Reset()         { *m = ChatModel{} }
func (m *ChatModel) String() string { return proto.CompactTextString(m) }
func (*ChatModel) ProtoMessage()    {}
func (*ChatModel) Descriptor() ([]byte, []int) {
	return fileDescriptor_8817812184a13374, []int{3}
}

func (m *ChatModel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatModel.Unmarshal(m, b)
}
func (m *ChatModel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatModel.Marshal(b, m, deterministic)
}
func (m *ChatModel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatModel.Merge(m, src)
}
func (m *ChatModel) XXX_Size() int {
	return xxx_messageInfo_ChatModel.Size(m)
}
func (m *ChatModel) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatModel.DiscardUnknown(m)
}

var xxx_messageInfo_ChatModel proto.InternalMessageInfo

func (m *ChatModel) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ChatModel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ChatModel) GetUsers() []*UserModel {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *ChatModel) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

type PostMessageRequest struct {
	Chat                 int64    `protobuf:"varint,1,opt,name=chat,proto3" json:"chat,omitempty"`
	Author               int64    `protobuf:"varint,2,opt,name=author,proto3" json:"author,omitempty"`
	Text                 string   `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostMessageRequest) Reset()         { *m = PostMessageRequest{} }
func (m *PostMessageRequest) String() string { return proto.CompactTextString(m) }
func (*PostMessageRequest) ProtoMessage()    {}
func (*PostMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8817812184a13374, []int{4}
}

func (m *PostMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostMessageRequest.Unmarshal(m, b)
}
func (m *PostMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostMessageRequest.Marshal(b, m, deterministic)
}
func (m *PostMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostMessageRequest.Merge(m, src)
}
func (m *PostMessageRequest) XXX_Size() int {
	return xxx_messageInfo_PostMessageRequest.Size(m)
}
func (m *PostMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostMessageRequest proto.InternalMessageInfo

func (m *PostMessageRequest) GetChat() int64 {
	if m != nil {
		return m.Chat
	}
	return 0
}

func (m *PostMessageRequest) GetAuthor() int64 {
	if m != nil {
		return m.Author
	}
	return 0
}

func (m *PostMessageRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type MessageModel struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Chat                 int64    `protobuf:"varint,2,opt,name=chat,proto3" json:"chat,omitempty"`
	Author               int64    `protobuf:"varint,3,opt,name=author,proto3" json:"author,omitempty"`
	Text                 string   `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	CreatedAt            int64    `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageModel) Reset()         { *m = MessageModel{} }
func (m *MessageModel) String() string { return proto.CompactTextString(m) }
func (*MessageModel) ProtoMessage()    {}
func (*MessageModel) Descriptor() ([]byte, []int) {
	return fileDescriptor_8817812184a13374, []int{5}
}

func (m *MessageModel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageModel.Unmarshal(m, b)
}
func (m *MessageModel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageModel.Marshal(b, m, deterministic)
}
func (m *MessageModel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageModel.Merge(m, src)
}
func (m *MessageModel) XXX_Size() int {
	return xxx_messageInfo_MessageModel.Size(m)
}
func (m *MessageModel) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageModel.DiscardUnknown(m)
}

var xxx_messageInfo_MessageModel proto.InternalMessageInfo

func (m *MessageModel) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MessageModel) GetChat() int64 {
	if m != nil {
		return m.Chat
	}
	return 0
}

func (m *MessageModel) GetAuthor() int64 {
	if m != nil {
		return m.Author
	}
	return 0
}

func (m *MessageModel) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *MessageModel) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

type ListUserChatsRequest struct {
	User                 int64    `protobuf:"varint,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUserChatsRequest) Reset()         { *m = ListUserChatsRequest{} }
func (m *ListUserChatsRequest) String() string { return proto.CompactTextString(m) }
func (*ListUserChatsRequest) ProtoMessage()    {}
func (*ListUserChatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8817812184a13374, []int{6}
}

func (m *ListUserChatsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUserChatsRequest.Unmarshal(m, b)
}
func (m *ListUserChatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUserChatsRequest.Marshal(b, m, deterministic)
}
func (m *ListUserChatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUserChatsRequest.Merge(m, src)
}
func (m *ListUserChatsRequest) XXX_Size() int {
	return xxx_messageInfo_ListUserChatsRequest.Size(m)
}
func (m *ListUserChatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUserChatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListUserChatsRequest proto.InternalMessageInfo

func (m *ListUserChatsRequest) GetUser() int64 {
	if m != nil {
		return m.User
	}
	return 0
}

type ListUserChatsResponse struct {
	Chats                []*ChatModel `protobuf:"bytes,1,rep,name=chats,proto3" json:"chats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ListUserChatsResponse) Reset()         { *m = ListUserChatsResponse{} }
func (m *ListUserChatsResponse) String() string { return proto.CompactTextString(m) }
func (*ListUserChatsResponse) ProtoMessage()    {}
func (*ListUserChatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8817812184a13374, []int{7}
}

func (m *ListUserChatsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUserChatsResponse.Unmarshal(m, b)
}
func (m *ListUserChatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUserChatsResponse.Marshal(b, m, deterministic)
}
func (m *ListUserChatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUserChatsResponse.Merge(m, src)
}
func (m *ListUserChatsResponse) XXX_Size() int {
	return xxx_messageInfo_ListUserChatsResponse.Size(m)
}
func (m *ListUserChatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUserChatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListUserChatsResponse proto.InternalMessageInfo

func (m *ListUserChatsResponse) GetChats() []*ChatModel {
	if m != nil {
		return m.Chats
	}
	return nil
}

type ListChatMessagesRequest struct {
	Chat                 int64    `protobuf:"varint,1,opt,name=chat,proto3" json:"chat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListChatMessagesRequest) Reset()         { *m = ListChatMessagesRequest{} }
func (m *ListChatMessagesRequest) String() string { return proto.CompactTextString(m) }
func (*ListChatMessagesRequest) ProtoMessage()    {}
func (*ListChatMessagesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8817812184a13374, []int{8}
}

func (m *ListChatMessagesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListChatMessagesRequest.Unmarshal(m, b)
}
func (m *ListChatMessagesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListChatMessagesRequest.Marshal(b, m, deterministic)
}
func (m *ListChatMessagesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListChatMessagesRequest.Merge(m, src)
}
func (m *ListChatMessagesRequest) XXX_Size() int {
	return xxx_messageInfo_ListChatMessagesRequest.Size(m)
}
func (m *ListChatMessagesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListChatMessagesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListChatMessagesRequest proto.InternalMessageInfo

func (m *ListChatMessagesRequest) GetChat() int64 {
	if m != nil {
		return m.Chat
	}
	return 0
}

type ListChatMessagesResponse struct {
	Messages             []*MessageModel `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListChatMessagesResponse) Reset()         { *m = ListChatMessagesResponse{} }
func (m *ListChatMessagesResponse) String() string { return proto.CompactTextString(m) }
func (*ListChatMessagesResponse) ProtoMessage()    {}
func (*ListChatMessagesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8817812184a13374, []int{9}
}

func (m *ListChatMessagesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListChatMessagesResponse.Unmarshal(m, b)
}
func (m *ListChatMessagesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListChatMessagesResponse.Marshal(b, m, deterministic)
}
func (m *ListChatMessagesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListChatMessagesResponse.Merge(m, src)
}
func (m *ListChatMessagesResponse) XXX_Size() int {
	return xxx_messageInfo_ListChatMessagesResponse.Size(m)
}
func (m *ListChatMessagesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListChatMessagesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListChatMessagesResponse proto.InternalMessageInfo

func (m *ListChatMessagesResponse) GetMessages() []*MessageModel {
	if m != nil {
		return m.Messages
	}
	return nil
}

func init() {
	proto.RegisterType((*UserCreateRequest)(nil), "dbProto.UserCreateRequest")
	proto.RegisterType((*UserModel)(nil), "dbProto.UserModel")
	proto.RegisterType((*ChatCreateRequest)(nil), "dbProto.ChatCreateRequest")
	proto.RegisterType((*ChatModel)(nil), "dbProto.ChatModel")
	proto.RegisterType((*PostMessageRequest)(nil), "dbProto.PostMessageRequest")
	proto.RegisterType((*MessageModel)(nil), "dbProto.MessageModel")
	proto.RegisterType((*ListUserChatsRequest)(nil), "dbProto.ListUserChatsRequest")
	proto.RegisterType((*ListUserChatsResponse)(nil), "dbProto.ListUserChatsResponse")
	proto.RegisterType((*ListChatMessagesRequest)(nil), "dbProto.ListChatMessagesRequest")
	proto.RegisterType((*ListChatMessagesResponse)(nil), "dbProto.ListChatMessagesResponse")
}

func init() { proto.RegisterFile("db.proto", fileDescriptor_8817812184a13374) }

var fileDescriptor_8817812184a13374 = []byte{
	// 445 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x54, 0x4d, 0x8f, 0xda, 0x30,
	0x14, 0x14, 0x09, 0x50, 0xf2, 0xe8, 0x17, 0x4f, 0xd0, 0xa2, 0x54, 0x54, 0xd4, 0x27, 0x54, 0xa9,
	0x54, 0xa5, 0xd7, 0xf6, 0x80, 0xe8, 0xb1, 0x54, 0x28, 0xfd, 0x3a, 0x56, 0x0e, 0xb1, 0x0a, 0xd2,
	0x42, 0xd8, 0xd8, 0xac, 0xb8, 0xec, 0x0f, 0xdf, 0xdb, 0xda, 0x8e, 0x09, 0x71, 0x30, 0xdc, 0x5e,
	0xcc, 0xbc, 0xf1, 0xcc, 0x78, 0x04, 0xb4, 0x92, 0x78, 0xbc, 0xcb, 0x52, 0x91, 0xe2, 0x93, 0x24,
	0x5e, 0xa8, 0x81, 0x7c, 0x84, 0xce, 0x6f, 0xce, 0xb2, 0x59, 0xc6, 0xa8, 0x60, 0x11, 0xbb, 0xdd,
	0x33, 0x2e, 0x30, 0x84, 0xd6, 0x5e, 0x1e, 0x6e, 0xe9, 0x86, 0xf5, 0x6b, 0xc3, 0xda, 0x28, 0x88,
	0x8a, 0x6f, 0xf2, 0x07, 0x02, 0xb5, 0x30, 0x4f, 0x13, 0x76, 0x83, 0xcf, 0xc1, 0x5b, 0x27, 0x1a,
	0xe2, 0x47, 0x72, 0xb2, 0x16, 0x3d, 0x7b, 0x11, 0x07, 0x00, 0x4b, 0x7d, 0x4b, 0xf2, 0x8f, 0x8a,
	0xbe, 0xaf, 0x77, 0x02, 0x73, 0x32, 0x15, 0xe4, 0x2b, 0x74, 0x66, 0x2b, 0x2a, 0x6c, 0x21, 0x08,
	0xf5, 0x92, 0x08, 0x3d, 0x63, 0x17, 0x1a, 0x8a, 0x93, 0xcb, 0x0b, 0x7c, 0x49, 0x91, 0x7f, 0x90,
	0x03, 0x04, 0x6a, 0xdd, 0x2d, 0xeb, 0x48, 0xe3, 0x95, 0x68, 0x46, 0x47, 0x1a, 0x5f, 0xd2, 0xb4,
	0x27, 0x38, 0x36, 0x89, 0x8c, 0x0b, 0x77, 0x86, 0xba, 0x22, 0xbc, 0x5e, 0x15, 0xfe, 0x0b, 0x70,
	0x91, 0x72, 0x31, 0x67, 0x9c, 0xd3, 0xff, 0x65, 0xe5, 0x4b, 0xa9, 0xc7, 0x88, 0xd0, 0x33, 0xbe,
	0x82, 0x26, 0xdd, 0x8b, 0x55, 0x9a, 0x69, 0x21, 0x7e, 0x64, 0xbe, 0x14, 0x56, 0xb0, 0x43, 0x9e,
	0x89, 0x94, 0xa7, 0x66, 0x72, 0x0f, 0x4f, 0x0d, 0xe3, 0x45, 0x4b, 0x9a, 0xdf, 0x73, 0xf2, 0xfb,
	0x4e, 0xfe, 0xfa, 0x89, 0xbf, 0x62, 0xaa, 0x51, 0x35, 0xf5, 0x1e, 0xba, 0xdf, 0xd7, 0x5c, 0xe8,
	0x6a, 0x48, 0x6a, 0x5e, 0xb2, 0xa5, 0x42, 0x39, 0xda, 0x52, 0x33, 0x99, 0x42, 0xaf, 0x82, 0xe5,
	0xbb, 0x74, 0xcb, 0x75, 0xc4, 0x4a, 0x17, 0x97, 0x68, 0x3b, 0xe2, 0xe2, 0xa5, 0xa2, 0x1c, 0x40,
	0x3e, 0xc0, 0x6b, 0x45, 0xa1, 0xcf, 0x73, 0xd7, 0xfc, 0x4a, 0x90, 0x64, 0x0e, 0xfd, 0x73, 0xb8,
	0xb9, 0xf4, 0x13, 0xb4, 0x36, 0xe6, 0x4c, 0x37, 0xa4, 0x3d, 0xe9, 0x15, 0xf7, 0x96, 0x13, 0x8d,
	0x0a, 0xd8, 0xe4, 0xc1, 0x83, 0x17, 0xdf, 0xa8, 0xa0, 0x31, 0xe5, 0xec, 0x27, 0xcb, 0xee, 0xd6,
	0x4b, 0x86, 0x5f, 0x00, 0xf2, 0x2a, 0x2a, 0x5b, 0x18, 0x5a, 0xed, 0xb0, 0x3a, 0x1a, 0x3a, 0x9a,
	0x73, 0xda, 0x56, 0x12, 0x4b, 0xdb, 0x67, 0x0d, 0x0f, 0x1d, 0xa1, 0xe0, 0x14, 0xda, 0xa5, 0x46,
	0xe1, 0x9b, 0x02, 0x72, 0xde, 0xb3, 0xd0, 0x6d, 0x0e, 0x7f, 0xc0, 0x33, 0xeb, 0x4d, 0x70, 0x50,
	0xe0, 0x5c, 0xef, 0x1a, 0xbe, 0xbd, 0xf4, 0xb3, 0x49, 0xf5, 0x2f, 0xbc, 0xac, 0x26, 0x8e, 0x43,
	0x6b, 0xc7, 0xf1, 0x76, 0xe1, 0xbb, 0x2b, 0x88, 0x9c, 0x38, 0x6e, 0xea, 0xff, 0xa3, 0xcf, 0x8f,
	0x01, 0x00, 0x00, 0xff, 0xff, 0xd0, 0x81, 0x77, 0x70, 0x9b, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DatabaseServiceClient is the client API for DatabaseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DatabaseServiceClient interface {
	CreateUser(ctx context.Context, in *UserCreateRequest, opts ...grpc.CallOption) (*UserModel, error)
	CreateChat(ctx context.Context, in *ChatCreateRequest, opts ...grpc.CallOption) (*ChatModel, error)
	PostMessage(ctx context.Context, in *PostMessageRequest, opts ...grpc.CallOption) (*MessageModel, error)
	ListUserChats(ctx context.Context, in *ListUserChatsRequest, opts ...grpc.CallOption) (*ListUserChatsResponse, error)
	ListChatMessages(ctx context.Context, in *ListChatMessagesRequest, opts ...grpc.CallOption) (*ListChatMessagesResponse, error)
}

type databaseServiceClient struct {
	cc *grpc.ClientConn
}

func NewDatabaseServiceClient(cc *grpc.ClientConn) DatabaseServiceClient {
	return &databaseServiceClient{cc}
}

func (c *databaseServiceClient) CreateUser(ctx context.Context, in *UserCreateRequest, opts ...grpc.CallOption) (*UserModel, error) {
	out := new(UserModel)
	err := c.cc.Invoke(ctx, "/dbProto.DatabaseService/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseServiceClient) CreateChat(ctx context.Context, in *ChatCreateRequest, opts ...grpc.CallOption) (*ChatModel, error) {
	out := new(ChatModel)
	err := c.cc.Invoke(ctx, "/dbProto.DatabaseService/CreateChat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseServiceClient) PostMessage(ctx context.Context, in *PostMessageRequest, opts ...grpc.CallOption) (*MessageModel, error) {
	out := new(MessageModel)
	err := c.cc.Invoke(ctx, "/dbProto.DatabaseService/PostMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseServiceClient) ListUserChats(ctx context.Context, in *ListUserChatsRequest, opts ...grpc.CallOption) (*ListUserChatsResponse, error) {
	out := new(ListUserChatsResponse)
	err := c.cc.Invoke(ctx, "/dbProto.DatabaseService/ListUserChats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseServiceClient) ListChatMessages(ctx context.Context, in *ListChatMessagesRequest, opts ...grpc.CallOption) (*ListChatMessagesResponse, error) {
	out := new(ListChatMessagesResponse)
	err := c.cc.Invoke(ctx, "/dbProto.DatabaseService/ListChatMessages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DatabaseServiceServer is the server API for DatabaseService service.
type DatabaseServiceServer interface {
	CreateUser(context.Context, *UserCreateRequest) (*UserModel, error)
	CreateChat(context.Context, *ChatCreateRequest) (*ChatModel, error)
	PostMessage(context.Context, *PostMessageRequest) (*MessageModel, error)
	ListUserChats(context.Context, *ListUserChatsRequest) (*ListUserChatsResponse, error)
	ListChatMessages(context.Context, *ListChatMessagesRequest) (*ListChatMessagesResponse, error)
}

// UnimplementedDatabaseServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDatabaseServiceServer struct {
}

func (*UnimplementedDatabaseServiceServer) CreateUser(ctx context.Context, req *UserCreateRequest) (*UserModel, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (*UnimplementedDatabaseServiceServer) CreateChat(ctx context.Context, req *ChatCreateRequest) (*ChatModel, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateChat not implemented")
}
func (*UnimplementedDatabaseServiceServer) PostMessage(ctx context.Context, req *PostMessageRequest) (*MessageModel, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostMessage not implemented")
}
func (*UnimplementedDatabaseServiceServer) ListUserChats(ctx context.Context, req *ListUserChatsRequest) (*ListUserChatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUserChats not implemented")
}
func (*UnimplementedDatabaseServiceServer) ListChatMessages(ctx context.Context, req *ListChatMessagesRequest) (*ListChatMessagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListChatMessages not implemented")
}

func RegisterDatabaseServiceServer(s *grpc.Server, srv DatabaseServiceServer) {
	s.RegisterService(&_DatabaseService_serviceDesc, srv)
}

func _DatabaseService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dbProto.DatabaseService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServiceServer).CreateUser(ctx, req.(*UserCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatabaseService_CreateChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServiceServer).CreateChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dbProto.DatabaseService/CreateChat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServiceServer).CreateChat(ctx, req.(*ChatCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatabaseService_PostMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServiceServer).PostMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dbProto.DatabaseService/PostMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServiceServer).PostMessage(ctx, req.(*PostMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatabaseService_ListUserChats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserChatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServiceServer).ListUserChats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dbProto.DatabaseService/ListUserChats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServiceServer).ListUserChats(ctx, req.(*ListUserChatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatabaseService_ListChatMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListChatMessagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServiceServer).ListChatMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dbProto.DatabaseService/ListChatMessages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServiceServer).ListChatMessages(ctx, req.(*ListChatMessagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DatabaseService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dbProto.DatabaseService",
	HandlerType: (*DatabaseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _DatabaseService_CreateUser_Handler,
		},
		{
			MethodName: "CreateChat",
			Handler:    _DatabaseService_CreateChat_Handler,
		},
		{
			MethodName: "PostMessage",
			Handler:    _DatabaseService_PostMessage_Handler,
		},
		{
			MethodName: "ListUserChats",
			Handler:    _DatabaseService_ListUserChats_Handler,
		},
		{
			MethodName: "ListChatMessages",
			Handler:    _DatabaseService_ListChatMessages_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "db.proto",
}
